# Generated by Django 4.1.7 on 2023-03-21 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="choices",
        ),
    ]
